config/routes.rb
Venn::Application.routes.draw do

  root 'teasers#index'

  resource :teaser, only: :create

end

app/models/user.rb
class User < ActiveRecord::Base

  valid_email_regex = /\A(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})\z/i

  validates :email, presence: true, :uniqueness => { :case_sensitive => false }, format: { with: valid_email_regex }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/teasers_controller.rb
class TeasersController < ApplicationController

  def index
  end

  def create
    user = User.create(email: params[:email])
    if user.errors.present?
      head :bad_request
    else
      head :created
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title="VENN"
    =stylesheet_link_tag    "application", media: "all"
    =javascript_include_tag "application"
    =csrf_meta_tags
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    %link{ href: '//fonts.googleapis.com/css?family=Montserrat:400', rel: 'stylesheet', type: 'text/css' }
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-48136321-1', 'venncloud.com');
      ga('send', 'pageview');
  %body
    - flash.each do |key, value|
      .message=value
    #content
      = yield

app/views/teasers/index.haml
.title1.fade.invisible
  %h1="venn"
.title2.fade.hidden.invisible
  = email_field_tag :email, nil, autocomplete: :off, :data => { remote: true, method: :post, url: teaser_path }
.line1
%h2.title1.fade.invisible
  ="what you can do does not fit into a job title"
%h2.title3.fade.hidden.invisible
  ="leave your e-mail to get notified"
%h2.title4.fade.hidden.invisible
  ="hit enter to submit"
  .status
    .loader.fade-fast.invisible.hidden
    .success.fade-fast.invisible.hidden
    .fail.fade-fast.invisible.hidden